version: '3.8'
services:
    app:
        image: cosmtrek/air
        working_dir: /app
        environment:
            PORT: 3000
        ports:
            - '3000:3000'
        volumes:
            - .:/app
